### PR TITLE
Update the entrypoint so docui will start by default

### PR DESCRIPTION
**Pull request by Red5d**

### CODE REVIEW

**Comment by skanehira** [comment]
Thank you PR.
When run docui on container, must be run sh.
If entrypoint run docui that not work.

```
panic: invalid dimensions

goroutine 1 [running]:
github.com/skanehira/docui/panel.(*Gui).init(0xc00007ccc0)
        /Users/skanehira/dev/go/src/github.com/skanehira/docui/panel/gui.go:198 +0xf57
github.com/skanehira/docui/panel.New(0x2, 0x842120)
        /Users/skanehira/dev/go/src/github.com/skanehira/docui/panel/gui.go:94 +0x138
main.main()
        /Users/skanehira/dev/go/src/github.com/skanehira/docui/main.go:13 +0x2e
```

I don't know cause but when entrypoint is sh then can work.
I plan to be able to start docui on container in the future.

**Comment by Red5d** [comment]
Hmm... Seems to be related to the go binary not detecting the size of the terminal window. I tried a few things with setting it in environment variables that I saw other people have tried, but wasn't able to get it working.

**Comment by skanehira** [comment]
@Red5d 
I solved this problem in https://github.com/skanehira/docui/issues/78
Please update your docui image and run it.

[asciicast](https://asciinema.org/a/225767)

**Comment by Red5d** [comment]
Thanks! Works for me now too.

**Pull request closed without merging**
