### PR TITLE
Add basicly CircleCI config

### PR DESCRIPTION
**Pull request by yamash723**
Hey guys, Thank you for making a so nice & cool tool.

BTW, I thought that CI was necessary for this repo, I wrote the CircleCI (for 2.1 version) configuration file.
Note: If you don't use CircleCI with this repo's policy, please close this PR.

🦍Need discuss🦍

**Which Lint tool do we need to use?**

- Currently is most simply, `golint ./...` only.
- Should we use `gometalinter`?
- Or, not lint check at CircleCI?
  - Ex: use [golangci](https://golangci.com/)?

I don't have deep experience on CircleCI & Golang.
If you have a good way, please tell me.

Thank's for reading.

### CODE REVIEW

**Comment by skanehira** [comment]
@yamash723 
Thanks PR.

>I don't have deep experience on CircleCI & Golang.
Me too.
Please wait a moment to check this PR.

**Comment by inductor** [comment]
Now that Dockerimage that builds the binary was merged, we should add that here as well, but if you'd like it on another PR I'll create one.

Something with https://circleci.com/docs/2.0/building-docker-images/ should work.

Example code(Unverified)

```yml:.circleci/config.yaml
  build-docker-image:
    parameters:
      go-version:
        type: string
    executor:
      name: default
      go-version: << parameters.go-version >>
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Install Docker client
          command: |
            set -x
            VER="18.09.0-ce"
            curl -L -o /tmp/docker-$VER.tgz https://download.docker.com/linux/static/stable/x86_64/docker-$VER.tgz
            tar -xz -C /tmp -f /tmp/docker-$VER.tgz
            mv /tmp/docker/* /usr/bin
      # build and push Docker image
      - run: |
          TAG=$CIRCLE_BUILD_NUM
          docker build -t skanehira/docui:$TAG .
          docker login -u $DOCKER_USER -p $DOCKER_PASS
          docker push skanehira/docui:$TAG
```

**Comment by yamash723** [comment]
@inductor 

Thanks your proposal. I will add build-docker-image job.

**Comment by yamash723** [comment]
> I will add build-docker-image job.

done!

## Changes from Example code

### Not setting `docker_layer_caching`

```
- setup_remote_docker:
      docker_layer_caching: true <-- Delete
```
**Reason**: This option is Premium Feature. 😭
https://circleci.com/docs/2.0/docker-layer-caching/

### Delete  `Install Docker client`

```
- run:
    name: Install Docker client
    command: |
      set -x
      VER="18.09.0-ce"
      curl -L -o /tmp/docker-$VER.tgz https://download.docker.com/linux/static/stable/x86_64/docker-$VER.tgz
      tar -xz -C /tmp -f /tmp/docker-$VER.tgz
      mv /tmp/docker/* /usr/bin
```

**Reason**: CircleCI recommended to "use a primary image that already has Docker"
https://circleci.com/docs/2.0/building-docker-images/

### Not push to Docker Hub

```
docker login -u $DOCKER_USER -p $DOCKER_PASS
docker push skanehira/docui:$TAG
```

**Reason**: I think that should be added when this repo has need to release in CircleCI.

**Comment by skanehira** [comment]
@yamash723 @inductor 
Thanks!
I'll merge this and use it in this week.

**Pull request merged**
